### ISSUE TITLE
TypeError: an integer is required (got type str)

### ISSUE THREAD

**Issue by rumputliar** [root-tanishq/userefuzz#1]
hello Mr
i tried your script but when i installed it it said TypeError
here the traceback :
_**python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    with open("README.md", "r", "utf-8") as f:
TypeError: an integer is required (got type str)**_

i already installed using pip too

**Comment by root-tanishq** [comment]
The issue is resolved and the tool is updated to 1.1.1 version
for ease of installation use the below command
```
sudo pip3 install userefuzz
```

**Comment by rohit0x5** [comment]
[✗]─[kali@kali]─[~]
└──╼ $userfuzz 
bash: userfuzz: command not found
┌─[✗]─[kali@kali]─[~]
└──╼ $sudo userfuzz
sudo: userfuzz: command not found
┌─[✗]─[kali@kali]─[~]
└──╼ $python3 userfuzz
python3: can't open file '/home/kali/userfuzz': [Errno 2] No such file or directory
┌─[✗]─[kali@kali]─[~]
└──╼ $python3 userfuzz -h
python3: can't open file '/home/kali/userfuzz': [Errno 2] No such file or directory

i got new error
