### ISSUE TITLE
showing problem

### ISSUE THREAD

**Issue by nijiinhell** [root-tanishq/userefuzz#11]
None of them showed the results like negative or positive. Just it starts and after a while it ends without anything. I tried pip install and github install type

**Comment by root-tanishq** [comment]
Pls provide screenshot

**Comment by fordrink** [comment]
same here

![2023-07-27_01-44](https://github.com/root-tanishq/userefuzz/assets/74085414/2db84339-fe26-4aae-a852-167a7766ba86)

**Comment by root-tanishq** [comment]
use -v for verbose as by default it only shows which are vulnerable

**Comment by fordrink** [comment]
hey @root-tanishq,
isn't working, I tested on kali,parrot,ubuntu
this is a new error on parrot..

![2023-09-24_15-50](https://github.com/root-tanishq/userefuzz/assets/74085414/45f96b3e-c3ad-4f1c-9150-aebef9e55c25)

kali and ubuntu are not showing anything

**Comment by root-tanishq** [comment]
What is it showing with pip try running sudo pip install userefuzz
