### ISSUE TITLE
Alot of false results

### ISSUE THREAD

**Issue by Abdelrahmanibrahim-prog** [root-tanishq/userefuzz#12]
It give me some results that the injection happen but when i try it do not work !
So what is the problem here ?

**Comment by root-tanishq** [comment]
yes there will be a lot of false positive as the tools completely relies on the sleep functionality of MySQL I think you should create a list and parse them once again 

I am thinking to fix this by re verification with different sleep time but due to of my busy schedule I am not able to update it

**Comment by root-tanishq** [comment]
Fixed it pls check
