### ISSUE TITLE
why can't i send request to burp?

### ISSUE THREAD

**Issue by mjulda** [root-tanishq/userefuzz#5]
why can't i send request to burp?
oh yeah, I'm using windows.
I downloaded Windows standalone

**Comment by root-tanishq** [comment]
can you share ss

**Comment by mjulda** [comment]
> 

![gambar](https://user-images.githubusercontent.com/49862728/205488976-b7faec9d-10c7-4f27-b624-e30240d38aa6.png)

**Comment by root-tanishq** [comment]
The request will be only send if the request is vulnerable otherwise not as in the ss the website is not having a time out of more than 10 sec that's why
