### ISSUE TITLE
 Multi headers

### ISSUE THREAD

**Issue by netwons** [root-tanishq/userefuzz#7]
How do I use custom Multi headers?

**Comment by root-tanishq** [comment]
Multi Header support is not there you have to use 2 instances on userefuzz


I will add it when I will have time
Thanks for suggesting

**Comment by netwons** [comment]
this code:
`cat payload | while read payload;do userefuzz.py -l gg -w 2 -o urls -p http://127.0.0.1:8080 -ch 'X-Forwarded-For' -i $payload -v -t; done`

help me

**Comment by netwons** [comment]
with add 
header = {'**X-Forwarded-For':args.inject** ,'User-Agent':args.inject , 'Referer': args.inject , 'X-Forwarded-For':args.inject , 'UseReFuzz':args.message }
